In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
#working_directory = r"/Users/stephanemasyn/Desktop/FinTech/Homeworks/PROJECTS/Project2"

#os.chdir(working_directory)
#print(os.getcwd())

## Create Training Set

In [3]:
#NFL2021OFF = pd.read_csv('./resources/NFL2021OFF.csv', names=['O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
#       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
#       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
#       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
#       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
#       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year'] )
#NFL2021OFF['Year'] = '2021'

NFL2020OFF = pd.read_csv('./resources/NFL2020OFF.csv', names=['O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year'] )
NFL2020OFF['Year'] = '2020'

NFL2019OFF = pd.read_csv('./resources/NFL2019OFF.csv', names=['D','O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year'] )
NFL2019OFF['Year'] = '2019'

NFL2018OFF = pd.read_csv('./resources/NFL2018OFF.csv', names=['D','O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year'] )
NFL2018OFF['Year'] = '2018'

NFL2017OFF = pd.read_csv('./resources/NFL2017OFF.csv', names=['D','O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year'] )
NFL2017OFF['Year'] = '2017'

NFL2016OFF = pd.read_csv('./resources/NFL2016OFF.csv', names=['D','O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year'] )
NFL2016OFF['Year'] = '2016'

NFL2015OFF = pd.read_csv('./resources/NFL2015OFF.csv', names=['D','O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year'] )
NFL2015OFF['Year'] = '2015'

In [4]:
NFL2015OFF.drop(columns=['D']).head()

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,...,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year
0,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Tot Yds & TO,Tot Yds & TO.1,Tot Yds & TO.2,Unnamed: 8,Unnamed: 9,...,Rushing.2,Rushing.3,Rushing.4,Penalties,Penalties.1,Penalties.2,Unnamed: 25,Unnamed: 26,Unnamed: 27,2015
1,Rk,Tm,G,PF,Yds,Ply,Y/P,TO,FL,1stD,...,TD,Y/A,1stD,Pen,Yds,1stPy,Sc%,TO%,EXP,2015
2,1,Carolina Panthers,16,500,5871,1060,5.5,19,9,357,...,19,4.3,136,103,887,24,42.9,9.6,114.88,2015
3,2,Arizona Cardinals,16,489,6533,1041,6.3,24,11,373,...,16,4.2,92,94,758,44,42.5,11.8,148.43,2015
4,3,New England Patriots,16,465,5991,1050,5.7,14,7,348,...,14,3.7,87,96,860,31,43.2,5.7,138.04,2015

In [5]:
NFL2015OFF = NFL2015OFF.drop([0,1])
NFL2016OFF = NFL2016OFF.drop([0,1])
NFL2017OFF = NFL2017OFF.drop([0,1])
NFL2018OFF = NFL2018OFF.drop([0,1])
NFL2019OFF = NFL2019OFF.drop([0,1])
NFL2020OFF = NFL2020OFF.drop([0,1])
#NFL2021OFF = NFL2021OFF.drop([0,1])
NFL2015OFF.head()

,D,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,...,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year
2,1.0,1,Carolina Panthers,16,500,5871,1060,5.5,19,9,...,19,4.3,136,103,887,24,42.9,9.6,114.88,2015
3,2.0,2,Arizona Cardinals,16,489,6533,1041,6.3,24,11,...,16,4.2,92,94,758,44,42.5,11.8,148.43,2015
4,3.0,3,New England Patriots,16,465,5991,1050,5.7,14,7,...,14,3.7,87,96,860,31,43.2,5.7,138.04,2015
5,4.0,4,Seattle Seahawks,16,423,6058,1035,5.9,16,8,...,10,4.5,128,117,1007,17,42,8.6,129.31,2015
6,5.0,5,Pittsburgh Steelers,16,423,6327,1011,6.3,28,7,...,16,4.4,91,94,868,33,40.5,13.7,22.98,2015

In [6]:
NFL2016OFF.drop(columns=['D']).head()

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,...,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year
2,1,Atlanta Falcons,16,540,6653,995,6.7,11,4,379,...,20,4.6,108,104,848,32,52.6,6.3,212.07,2016
3,2,New Orleans Saints,16,469,6816,1105,6.2,24,9,395,...,17,4.3,105,107,969,25,45.9,12.7,76.86,2016
4,3,New England Patriots,16,441,6180,1056,5.9,11,9,351,...,19,3.9,109,93,819,39,42.9,4.9,113.38,2016
5,4,Green Bay Packers,16,432,5900,1029,5.7,17,9,349,...,11,4.5,91,100,827,36,43.8,9.1,115.16,2016
6,5,Dallas Cowboys,16,421,6027,1010,6,15,9,358,...,24,4.8,142,105,879,25,43.9,8.7,86.3,2016

In [7]:
NFL2017OFF.drop(columns=['D']).head()

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,...,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year
2,1,Los Angeles Rams,16,478,5784,1000,5.8,21,14,311,...,17,4.3,97,107,922,29,45.3,9.5,-43.18,2017
3,2,New England Patriots,16,458,6307,1070,5.9,12,4,389,...,16,4.2,107,95,835,50,49.4,6.9,114.84,2017
4,3,Philadelphia Eagles,16,457,5852,1073,5.5,20,11,338,...,9,4.5,108,116,962,37,40.3,9.4,21.06,2017
5,4,New Orleans Saints,16,448,6259,1000,6.3,18,10,332,...,23,4.7,111,105,967,20,44.6,9.1,7.38,2017
6,5,Jacksonville Jaguars,16,417,5855,1078,5.4,23,10,332,...,18,4.3,101,112,936,38,34.7,11.1,-36.01,2017

In [8]:
NFL2018OFF.drop(columns=['D']).head()

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,...,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year
2,1,Kansas City Chiefs,16,565,6810,996,6.8,18,6,384,...,16,4.8,108,137,1152,37,52.6,10.5,298.14,2018
3,2,Los Angeles Rams,16,527,6738,1060,6.4,19,7,401,...,23,4.9,134,96,878,31,48.6,9.8,239.79,2018
4,3,New Orleans Saints,16,504,6067,1010,6,16,9,377,...,26,4.3,134,94,939,33,51.8,9.5,237.73,2018
5,4,New England Patriots,16,436,6295,1073,5.9,18,7,365,...,18,4.3,131,93,744,28,40.8,9.2,190.96,2018
6,5,Indianapolis Colts,16,433,6179,1070,5.8,24,9,371,...,13,4.2,96,120,953,38,41.2,13.2,140.47,2018

In [9]:
NFL2019OFF.drop(columns=['D']).head()

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,...,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year
2,1,Baltimore Ravens,16,531,6521,1064,6.1,15,7,386,...,21,5.5,188,109,867,27,52.1,8.6,245.99,2019
3,2,San Francisco 49ers,16,479,6097,1012,6,23,10,336,...,23,4.6,110,105,939,31,44.3,12,123.17,2019
4,3,Tampa Bay Buccaneers,16,458,6366,1086,5.9,41,11,353,...,15,3.7,81,133,1111,28,38.3,20.7,44,2019
5,4,New Orleans Saints,16,458,5982,1011,5.9,8,2,347,...,12,4.3,97,120,1036,20,47,4.2,167.04,2019
6,5,Kansas City Chiefs,16,451,6067,976,6.2,15,10,350,...,16,4.2,93,107,1029,46,49.4,8,217.32,2019

In [10]:
NFL2020OFF.head()

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,...,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year
2,1,Green Bay Packers,16,509,6224,990,6.3,11,6,358,...,16,4.8,114,84,684,28,49.7,5.6,290.75,2020
3,2,Buffalo Bills,16,501,6343,1034,6.1,22,11,397,...,16,4.2,119,102,941,38,49.4,11.8,228.66,2020
4,3,Tampa Bay Buccaneers,16,492,6145,1017,6.0,17,5,364,...,16,4.1,82,84,715,44,47.8,8.9,246.24,2020
5,4,Tennessee Titans,16,491,6343,1031,6.2,12,5,381,...,26,5.2,142,86,783,36,47.9,7.2,245.01,2020
6,5,New Orleans Saints,16,482,6023,1045,5.8,17,9,367,...,30,4.6,147,98,1005,21,45.5,9.0,176.94,2020

In [11]:
#NFL2021OFF.head()

In [12]:
# Merge response data together
data_frames = [ NFL2020OFF[0:32], NFL2019OFF[0:32], NFL2018OFF[0:32], NFL2017OFF[0:32], NFL2016OFF[0:32], NFL2015OFF[0:32]]
#NFL2021OFF[0:32],
O_total = pd.concat(data_frames)

In [13]:

O_total['Year'] = O_total['Year'].astype('int')

In [14]:
O_total.head()

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,...,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year,D
2,1,Green Bay Packers,16,509,6224,990,6.3,11,6,358,...,4.8,114,84,684,28,49.7,5.6,290.75,2020,NaN
3,2,Buffalo Bills,16,501,6343,1034,6.1,22,11,397,...,4.2,119,102,941,38,49.4,11.8,228.66,2020,NaN
4,3,Tampa Bay Buccaneers,16,492,6145,1017,6.0,17,5,364,...,4.1,82,84,715,44,47.8,8.9,246.24,2020,NaN
5,4,Tennessee Titans,16,491,6343,1031,6.2,12,5,381,...,5.2,142,86,783,36,47.9,7.2,245.01,2020,NaN
6,5,New Orleans Saints,16,482,6023,1045,5.8,17,9,367,...,4.6,147,98,1005,21,45.5,9.0,176.94,2020,NaN

In [15]:
#NFL2021DEF = pd.read_csv('./resources/NFL2021DEF.csv', names=['O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
#       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
#       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
#       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
#       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
#       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year'] )
#NFL2021DEF['Year'] = '2021'

NFL2020DEF = pd.read_csv('./resources/NFL2020DEF.csv', names=['D_Rank', 'Team', 'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards',
       'D_Plays', 'D_Y/Play', 'D_TD', 'D_Fumbles_Lost',
       'D_1st_D', 'D_P_Completions', 'D_P_Attempts', 'D_P_Yards', 'D_P_TD',
       'D_P_Int', 'D_P_Y/PA', 'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards',
       'D_R_TD', 'D_R_Y/A', 'D_R_1st_D', 'D_Pe', 'D_Pe_Yards',
       'D_Pe_1st_D', 'D_Scoring_Drives', 'D_TD_%', 'D_Expected_Points', 'Year'] )
NFL2020DEF['Year'] = '2020'

NFL2019DEF = pd.read_csv('./resources/NFL2019DEF.csv', names=['D','D_Rank', 'Team', 'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards',
       'D_Plays', 'D_Y/Play', 'D_TD', 'D_Fumbles_Lost',
       'D_1st_D', 'D_P_Completions', 'D_P_Attempts', 'D_P_Yards', 'D_P_TD',
       'D_P_Int', 'D_P_Y/PA', 'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards',
       'D_R_TD', 'D_R_Y/A', 'D_R_1st_D', 'D_Pe', 'D_Pe_Yards',
       'D_Pe_1st_D', 'D_Scoring_Drives', 'D_TD_%', 'D_Expected_Points', 'Year'] )
NFL2019DEF['Year'] = '2019'

NFL2018DEF = pd.read_csv('./resources/NFL2018DEF.csv', names=['D','D_Rank', 'Team', 'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards',
       'D_Plays', 'D_Y/Play', 'D_TD', 'D_Fumbles_Lost',
       'D_1st_D', 'D_P_Completions', 'D_P_Attempts', 'D_P_Yards', 'D_P_TD',
       'D_P_Int', 'D_P_Y/PA', 'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards',
       'D_R_TD', 'D_R_Y/A', 'D_R_1st_D', 'D_Pe', 'D_Pe_Yards',
       'D_Pe_1st_D', 'D_Scoring_Drives', 'D_TD_%', 'D_Expected_Points', 'Year'] )
NFL2018DEF['Year'] = '2018'

NFL2017DEF = pd.read_csv('./resources/NFL2017DEF.csv', names=['D','D_Rank', 'Team', 'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards',
       'D_Plays', 'D_Y/Play', 'D_TD', 'D_Fumbles_Lost',
       'D_1st_D', 'D_P_Completions', 'D_P_Attempts', 'D_P_Yards', 'D_P_TD',
       'D_P_Int', 'D_P_Y/PA', 'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards',
       'D_R_TD', 'D_R_Y/A', 'D_R_1st_D', 'D_Pe', 'D_Pe_Yards',
       'D_Pe_1st_D', 'D_Scoring_Drives', 'D_TD_%', 'D_Expected_Points', 'Year'] )
NFL2017DEF['Year'] = '2017'

NFL2016DEF = pd.read_csv('./resources/NFL2016DEF.csv', names=['D','D_Rank', 'Team', 'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards',
       'D_Plays', 'D_Y/Play', 'D_TD', 'D_Fumbles_Lost',
       'D_1st_D', 'D_P_Completions', 'D_P_Attempts', 'D_P_Yards', 'D_P_TD',
       'D_P_Int', 'D_P_Y/PA', 'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards',
       'D_R_TD', 'D_R_Y/A', 'D_R_1st_D', 'D_Pe', 'D_Pe_Yards',
       'D_Pe_1st_D', 'D_Scoring_Drives', 'D_TD_%', 'D_Expected_Points', 'Year'] )
NFL2016DEF['Year'] = '2016'

NFL2015DEF = pd.read_csv('./resources/NFL2015DEF.csv', names=['D','D_Rank', 'Team', 'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards',
       'D_Plays', 'D_Y/Play', 'D_TD', 'D_Fumbles_Lost',
       'D_1st_D', 'D_P_Completions', 'D_P_Attempts', 'D_P_Yards', 'D_P_TD',
       'D_P_Int', 'D_P_Y/PA', 'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards',
       'D_R_TD', 'D_R_Y/A', 'D_R_1st_D', 'D_Pe', 'D_Pe_Yards',
       'D_Pe_1st_D', 'D_Scoring_Drives', 'D_TD_%', 'D_Expected_Points', 'Year'] )
NFL2015DEF['Year'] = '2015'

In [16]:
NFL2015DEF = NFL2015DEF.drop([0,1])
NFL2016DEF = NFL2016DEF.drop([0,1])
NFL2017DEF = NFL2017DEF.drop([0,1])
NFL2018DEF = NFL2018DEF.drop([0,1])
NFL2019DEF = NFL2019DEF.drop([0,1])
NFL2020DEF = NFL2020DEF.drop([0,1])
#NFL2021DEF = NFL2021DEF.drop([0,1])
NFL2015DEF.head()

,D,D_Rank,Team,D_Games_Played,D_Points_Allowed,D_Total_Yards,D_Plays,D_Y/Play,D_TD,D_Fumbles_Lost,...,D_R_TD,D_R_Y/A,D_R_1st_D,D_Pe,D_Pe_Yards,D_Pe_1st_D,D_Scoring_Drives,D_TD_%,D_Expected_Points,Year
2,1.0,1,Seattle Seahawks,16,277,4668,947,4.9,23,9,...,10,3.6,71,94,795,27,29.3,13.2,59.08,2015
3,2.0,2,Cincinnati Bengals,16,279,5453,1032,5.3,28,7,...,8,4.3,74,116,1063,31,28.9,15,40.96,2015
4,3.0,3,Kansas City Chiefs,16,287,5269,1037,5.1,29,7,...,7,4.1,86,110,941,34,27.3,15.3,105.76,2015
5,4.0,4,Denver Broncos,16,296,4530,1033,4.4,27,13,...,10,3.3,81,104,773,46,26.9,11.9,141.86,2015
6,5.0,5,Minnesota Vikings,16,302,5510,1015,5.4,22,9,...,7,4.3,94,109,875,35,33.3,11.9,11.53,2015

In [17]:
NFL2015DEF.drop(columns=['D']).head()
NFL2016DEF.drop(columns=['D']).head()
NFL2017DEF.drop(columns=['D']).head()
NFL2018DEF.drop(columns=['D']).head()
NFL2019DEF.drop(columns=['D']).head()

,D_Rank,Team,D_Games_Played,D_Points_Allowed,D_Total_Yards,D_Plays,D_Y/Play,D_TD,D_Fumbles_Lost,D_1st_D,...,D_R_TD,D_R_Y/A,D_R_1st_D,D_Pe,D_Pe_Yards,D_Pe_1st_D,D_Scoring_Drives,D_TD_%,D_Expected_Points,Year
2,1,New England Patriots,16,225,4414,948,4.7,36,11,261,...,7,4.2,72,107,920,39,19.4,17.3,165.75,2019
3,2,Buffalo Bills,16,259,4772,985,4.8,23,9,295,...,12,4.3,93,94,815,33,23.6,12.4,39.85,2019
4,3,Baltimore Ravens,16,282,4809,921,5.2,25,12,276,...,12,4.4,74,97,795,39,32.9,14.6,16.61,2019
5,4,Chicago Bears,16,298,5186,1017,5.1,19,9,306,...,16,3.9,86,113,923,30,31.3,10.8,-4.15,2019
6,5,Minnesota Vikings,16,303,5465,1053,5.2,31,14,324,...,8,4.3,78,83,713,31,34.5,17,-7.88,2019

In [18]:
# Merge response data together
data_frames_2 = [ NFL2020DEF[0:32], NFL2019DEF[0:32], NFL2018DEF[0:32], NFL2017DEF[0:32], NFL2016DEF[0:32], NFL2015DEF[0:32]]
#NFL2021DEF[0:32],
D_total = pd.concat(data_frames_2)

In [19]:
#D_total.columns = ['D_Rank', 'Team', 'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards',
#       'D_Plays', 'D_Y/Play', 'D_TD', 'D_Fumbles_Lost',
 #      'D_1st_D', 'D_P_Completions', 'D_P_Attempts', 'D_P_Yards', 'D_P_TD',
 #      'D_P_Int', 'D_P_Y/PA', 'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards',
  #     'D_R_TD', 'D_R_Y/A', 'D_R_1st_D', 'D_Pe', 'D_Pe_Yards',
  #     'D_Pe_1st_D', 'D_Scoring_Drives', 'D_TD_%', 'D_Expected_Points', 'Year']

D_total['Year'] = O_total['Year'].astype('int')

In [20]:
D_total.tail()

,D_Rank,Team,D_Games_Played,D_Points_Allowed,D_Total_Yards,D_Plays,D_Y/Play,D_TD,D_Fumbles_Lost,D_1st_D,...,D_R_Y/A,D_R_1st_D,D_Pe,D_Pe_Yards,D_Pe_1st_D,D_Scoring_Drives,D_TD_%,D_Expected_Points,Year,D
29,28,Philadelphia Eagles,16,430,6426,1148,5.6,26,11,365,...,4.5,100,123,1049,26,36,11.8,-74.73,2015,28.0
30,29,Cleveland Browns,16,432,6067,998,6.1,21,10,321,...,4.5,104,108,833,31,41.9,11.7,-95.96,2015,29.0
31,30,New York Giants,16,442,6725,1105,6.1,28,13,367,...,4.4,104,120,1077,27,40.5,14.2,-103.42,2015,30.0
32,31,Jacksonville Jaguars,16,448,6000,1102,5.4,18,9,362,...,3.7,102,114,989,38,38.1,8.8,-75.65,2015,31.0
33,32,New Orleans Saints,16,476,6615,997,6.6,22,13,380,...,4.9,103,114,887,54,43.9,11.7,-180.12,2015,32.0

In [21]:
trainSet = O_total.merge(D_total, on = ['Team', 'Year'])

## Create Test Set

In [22]:
pd.set_option('display.max_columns', 500)

NFL2021OFF = pd.read_csv('./resources/NFL2021OFF.csv')
NFL2021OFF['Year'] = '2021'

NFL2021DEF = pd.read_csv('./resources/NFL2021DEF.csv')
NFL2021DEF['Year'] = '2021'

NFL2021OFF = NFL2021OFF[1:33]
NFL2021OFF.columns = ['O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year']

NFL2021DEF = NFL2021DEF[1:33]
NFL2021DEF.columns = ['D_Rank', 'Team', 'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards',
       'D_Plays', 'D_Y/Play', 'D_TD', 'D_Fumbles_Lost',
       'D_1st_D', 'D_P_Completions', 'D_P_Attempts', 'D_P_Yards', 'D_P_TD',
       'D_P_Int', 'D_P_Y/PA', 'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards',
       'D_R_TD', 'D_R_Y/A', 'D_R_1st_D', 'D_Pe', 'D_Pe_Yards',
       'D_Pe_1st_D', 'D_Scoring_Drives', 'D_TD_%', 'D_Expected_Points', 'Year']

testSet = NFL2021OFF.merge(NFL2021DEF, on = ['Team', 'Year'])
testSet.head()

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,O_P_Completions,O_P_Attempts,O_P_Yards,O_P_TD,O_P_Int,O_P_Y/PA,O_P_Passing_1st_D,O_R_Att,O_R_Yards,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year,D_Rank,D_Games_Played,D_Points_Allowed,D_Total_Yards,D_Plays,D_Y/Play,D_TD,D_Fumbles_Lost,D_1st_D,D_P_Completions,D_P_Attempts,D_P_Yards,D_P_TD,D_P_Int,D_P_Y/PA,D_P_Passing_1st_D,D_R_Att,D_R_Yards,D_R_TD,D_R_Y/A,D_R_1st_D,D_Pe,D_Pe_Yards,D_Pe_1st_D,D_Scoring_Drives,D_TD_%,D_Expected_Points
0,1,Dallas Cowboys,16,479,6444,1092,5.9,20,9,368,422,619,4496,35,11,6.9,235,441,1948,13,4.4,102,122,1059,31,41.8,10.4,129.5,2021,7,16,332,5652,1012,5.6,33,8,305,344,578,3883,22,25,6.3,180,396,1769,12,4.5,90,118,943,35,31.6,17.1,31.06
1,2,Tampa Bay Buccaneers,16,470,6492,1079,6,19,7,383,463,692,4905,40,12,6.9,258,365,1587,16,4.3,100,95,864,25,43.4,10.4,194.61,2021,10,16,336,5318,1022,5.2,27,11,326,416,637,3855,24,16,5.7,204,340,1463,11,4.3,88,78,625,34,34.1,14.5,-25.01
2,3,Buffalo Bills,16,456,6069,1064,5.7,22,6,373,390,609,4030,34,16,6.3,221,428,2039,19,4.8,127,109,940,25,45.9,12.2,142.89,2021,2,16,279,4584,968,4.7,30,11,281,290,510,2766,11,19,5.1,135,425,1818,19,4.3,107,98,817,39,28.9,15.6,55.21
3,4,Kansas City Chiefs,16,452,6356,1060,6,25,12,391,421,631,4536,35,13,6.9,248,402,1820,16,4.5,113,106,880,30,48.1,14.4,183.83,2021,13,16,340,5908,1006,5.9,28,13,345,388,585,4100,27,15,6.7,200,391,1808,12,4.6,113,110,866,32,36.6,16.1,-95.51
4,5,Cincinnati Bengals,16,444,5963,995,6,21,7,326,369,526,4300,35,14,7.5,204,418,1663,16,4,90,68,588,32,43.6,10.5,119.1,2021,18,16,355,5588,1009,5.5,19,7,315,403,602,4051,24,12,6.3,205,366,1537,14,4.2,92,112,900,18,34.3,10.7,-27.17

In [23]:
adjusted_columns = ['O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_TO', 'O_Fumbles_Lost', 'O_1st_D',
       'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD', 'O_P_Int',
       'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards', 'O_R_TD',
       'O_R_1st_D', 'O_Pe', 'O_Pe_Yards', 'O_Pe_1st_D',
       'O_Scoring_Drives', 'O_Expected_Points', 
       'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards', 'D_Plays',
       'D_TD', 'D_Fumbles_Lost', 'D_1st_D', 'D_P_Completions',
       'D_P_Attempts', 'D_P_Yards', 'D_P_TD', 'D_P_Int',
       'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards', 'D_R_TD', 
       'D_R_1st_D', 'D_Pe', 'D_Pe_Yards', 'D_Pe_1st_D', 'D_Scoring_Drives',
       'D_Expected_Points']

for col in [adjusted_columns]:
    testSet[col] = testSet[col].astype('float')

testSet['O_Games_Played'] = testSet['O_Games_Played'].astype('int')
adjuster = 16 / testSet['O_Games_Played'] 

testSet[adjusted_columns] = testSet[adjusted_columns].mul(adjuster, axis = 0)
testSet.head()

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,O_P_Completions,O_P_Attempts,O_P_Yards,O_P_TD,O_P_Int,O_P_Y/PA,O_P_Passing_1st_D,O_R_Att,O_R_Yards,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year,D_Rank,D_Games_Played,D_Points_Allowed,D_Total_Yards,D_Plays,D_Y/Play,D_TD,D_Fumbles_Lost,D_1st_D,D_P_Completions,D_P_Attempts,D_P_Yards,D_P_TD,D_P_Int,D_P_Y/PA,D_P_Passing_1st_D,D_R_Att,D_R_Yards,D_R_TD,D_R_Y/A,D_R_1st_D,D_Pe,D_Pe_Yards,D_Pe_1st_D,D_Scoring_Drives,D_TD_%,D_Expected_Points
0,1,Dallas Cowboys,16,479.0,6444.0,1092.0,5.9,20.0,9.0,368.0,422.0,619.0,4496.0,35.0,11.0,6.9,235.0,441.0,1948.0,13.0,4.4,102.0,122.0,1059.0,31.0,41.8,10.4,129.50,2021,7,16.0,332.0,5652.0,1012.0,5.6,33.0,8.0,305.0,344.0,578.0,3883.0,22.0,25.0,6.3,180.0,396.0,1769.0,12.0,4.5,90.0,118.0,943.0,35.0,31.6,17.1,31.06
1,2,Tampa Bay Buccaneers,16,470.0,6492.0,1079.0,6,19.0,7.0,383.0,463.0,692.0,4905.0,40.0,12.0,6.9,258.0,365.0,1587.0,16.0,4.3,100.0,95.0,864.0,25.0,43.4,10.4,194.61,2021,10,16.0,336.0,5318.0,1022.0,5.2,27.0,11.0,326.0,416.0,637.0,3855.0,24.0,16.0,5.7,204.0,340.0,1463.0,11.0,4.3,88.0,78.0,625.0,34.0,34.1,14.5,-25.01
2,3,Buffalo Bills,16,456.0,6069.0,1064.0,5.7,22.0,6.0,373.0,390.0,609.0,4030.0,34.0,16.0,6.3,221.0,428.0,2039.0,19.0,4.8,127.0,109.0,940.0,25.0,45.9,12.2,142.89,2021,2,16.0,279.0,4584.0,968.0,4.7,30.0,11.0,281.0,290.0,510.0,2766.0,11.0,19.0,5.1,135.0,425.0,1818.0,19.0,4.3,107.0,98.0,817.0,39.0,28.9,15.6,55.21
3,4,Kansas City Chiefs,16,452.0,6356.0,1060.0,6,25.0,12.0,391.0,421.0,631.0,4536.0,35.0,13.0,6.9,248.0,402.0,1820.0,16.0,4.5,113.0,106.0,880.0,30.0,48.1,14.4,183.83,2021,13,16.0,340.0,5908.0,1006.0,5.9,28.0,13.0,345.0,388.0,585.0,4100.0,27.0,15.0,6.7,200.0,391.0,1808.0,12.0,4.6,113.0,110.0,866.0,32.0,36.6,16.1,-95.51
4,5,Cincinnati Bengals,16,444.0,5963.0,995.0,6,21.0,7.0,326.0,369.0,526.0,4300.0,35.0,14.0,7.5,204.0,418.0,1663.0,16.0,4,90.0,68.0,588.0,32.0,43.6,10.5,119.10,2021,18,16.0,355.0,5588.0,1009.0,5.5,19.0,7.0,315.0,403.0,602.0,4051.0,24.0,12.0,6.3,205.0,366.0,1537.0,14.0,4.2,92.0,112.0,900.0,18.0,34.3,10.7,-27.17

In [24]:
testSet.to_csv('./resources/TestSet3.csv', index = False)

In [25]:
testSet['Year'] = testSet['Year'].astype('int')


mydata = pd.concat([testSet, trainSet])

In [26]:
mydata.head()

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,O_P_Completions,O_P_Attempts,O_P_Yards,O_P_TD,O_P_Int,O_P_Y/PA,O_P_Passing_1st_D,O_R_Att,O_R_Yards,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year,D_Rank,D_Games_Played,D_Points_Allowed,D_Total_Yards,D_Plays,D_Y/Play,D_TD,D_Fumbles_Lost,D_1st_D,D_P_Completions,D_P_Attempts,D_P_Yards,D_P_TD,D_P_Int,D_P_Y/PA,D_P_Passing_1st_D,D_R_Att,D_R_Yards,D_R_TD,D_R_Y/A,D_R_1st_D,D_Pe,D_Pe_Yards,D_Pe_1st_D,D_Scoring_Drives,D_TD_%,D_Expected_Points,D_x,D_y
0,1,Dallas Cowboys,16,479.0,6444.0,1092.0,5.9,20.0,9.0,368.0,422.0,619.0,4496.0,35.0,11.0,6.9,235.0,441.0,1948.0,13.0,4.4,102.0,122.0,1059.0,31.0,41.8,10.4,129.5,2021,7,16.0,332.0,5652.0,1012.0,5.6,33.0,8.0,305.0,344.0,578.0,3883.0,22.0,25.0,6.3,180.0,396.0,1769.0,12.0,4.5,90.0,118.0,943.0,35.0,31.6,17.1,31.06,NaN,NaN
1,2,Tampa Bay Buccaneers,16,470.0,6492.0,1079.0,6,19.0,7.0,383.0,463.0,692.0,4905.0,40.0,12.0,6.9,258.0,365.0,1587.0,16.0,4.3,100.0,95.0,864.0,25.0,43.4,10.4,194.61,2021,10,16.0,336.0,5318.0,1022.0,5.2,27.0,11.0,326.0,416.0,637.0,3855.0,24.0,16.0,5.7,204.0,340.0,1463.0,11.0,4.3,88.0,78.0,625.0,34.0,34.1,14.5,-25.01,NaN,NaN
2,3,Buffalo Bills,16,456.0,6069.0,1064.0,5.7,22.0,6.0,373.0,390.0,609.0,4030.0,34.0,16.0,6.3,221.0,428.0,2039.0,19.0,4.8,127.0,109.0,940.0,25.0,45.9,12.2,142.89,2021,2,16.0,279.0,4584.0,968.0,4.7,30.0,11.0,281.0,290.0,510.0,2766.0,11.0,19.0,5.1,135.0,425.0,1818.0,19.0,4.3,107.0,98.0,817.0,39.0,28.9,15.6,55.21,NaN,NaN
3,4,Kansas City Chiefs,16,452.0,6356.0,1060.0,6,25.0,12.0,391.0,421.0,631.0,4536.0,35.0,13.0,6.9,248.0,402.0,1820.0,16.0,4.5,113.0,106.0,880.0,30.0,48.1,14.4,183.83,2021,13,16.0,340.0,5908.0,1006.0,5.9,28.0,13.0,345.0,388.0,585.0,4100.0,27.0,15.0,6.7,200.0,391.0,1808.0,12.0,4.6,113.0,110.0,866.0,32.0,36.6,16.1,-95.51,NaN,NaN
4,5,Cincinnati Bengals,16,444.0,5963.0,995.0,6,21.0,7.0,326.0,369.0,526.0,4300.0,35.0,14.0,7.5,204.0,418.0,1663.0,16.0,4,90.0,68.0,588.0,32.0,43.6,10.5,119.1,2021,18,16.0,355.0,5588.0,1009.0,5.5,19.0,7.0,315.0,403.0,602.0,4051.0,24.0,12.0,6.3,205.0,366.0,1537.0,14.0,4.2,92.0,112.0,900.0,18.0,34.3,10.7,-27.17,NaN,NaN

In [27]:
columns = ['O_Games_Played', 'O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost', 'O_1st_D',
       'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD', 'O_P_Int',
       'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards', 'O_R_TD',
       'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards', 'O_Pe_1st_D',
       'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 
       'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards', 'D_Plays',
       'D_Y/Play', 'D_TD', 'D_Fumbles_Lost', 'D_1st_D', 'D_P_Completions',
       'D_P_Attempts', 'D_P_Yards', 'D_P_TD', 'D_P_Int', 'D_P_Y/PA',
       'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards', 'D_R_TD', 'D_R_Y/A',
       'D_R_1st_D', 'D_Pe', 'D_Pe_Yards', 'D_Pe_1st_D', 'D_Scoring_Drives',
       'D_TD_%', 'D_Expected_Points']

for col in [columns]:
    mydata[col] = mydata[col].astype('float')

## Append Superbowl Winners

In [28]:
mydata['Superbowl'] = 0

In [29]:
SBwinners = pd.read_csv('./resources/SuperbowlWinners.csv')
SBwinners.drop(columns=['Unnamed: 0'], inplace=True)

In [30]:
SBwinners.head()

,Date,SB,Winner,Pts,Loser,Pts.1,MVP,Stadium,City,State
0,Feb 3 2019,LIII (53),New England Patriots,13,Los Angeles Rams,3,Julian Edelman,Mercedez-Benz Stadium,Atlanta,Georgia
1,Feb 4 2018,LII (52),Philadelphia Eagles,41,New England Patriots,33,Nick Foles,U.S. Bank Stadium,Minneapolis,Minnesota
2,Feb 5 2017,LI (51),New England Patriots,34,Atlanta Falcons,28,Tom Brady,NRG Stadium,Houston,Texas
3,Feb 7 2016,50,Denver Broncos,24,Carolina Panthers,10,Von Miller,Levi's Stadium,Santa Clara,California
4,Feb 1 2015,XLIX (49),New England Patriots,28,Seattle Seahawks,24,Tom Brady,University of Phoenix Stadium,Glendale,Arizona

In [31]:
SBwinners.Date = pd.to_datetime(SBwinners.Date)

In [32]:
SBwinners['Year'] = pd.DatetimeIndex(SBwinners['Date']).year
SBwinners = SBwinners[['Year', 'Winner']]
SBwinners.tail()

    Year              Winner
48  1971     Baltimore Colts
49  1970  Kansas City Chiefs
50  1969       New York Jets
51  1968   Green Bay Packers
52  1967   Green Bay Packers

In [33]:
SBwinners['Year'] = SBwinners['Year'] - 1
SBwinners.Year = SBwinners.Year.astype('object')
SBwinners['Superbowl'] = 1

In [34]:
SBwinners.Year = SBwinners.Year.astype('int')
mydata.Year = mydata.Year.astype('int')

test = pd.merge(mydata, SBwinners, left_on = ['Year','Team'], right_on = ['Year', 'Winner'], how = 'left')
test.head()

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,O_P_Completions,O_P_Attempts,O_P_Yards,O_P_TD,O_P_Int,O_P_Y/PA,O_P_Passing_1st_D,O_R_Att,O_R_Yards,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year,D_Rank,D_Games_Played,D_Points_Allowed,D_Total_Yards,D_Plays,D_Y/Play,D_TD,D_Fumbles_Lost,D_1st_D,D_P_Completions,D_P_Attempts,D_P_Yards,D_P_TD,D_P_Int,D_P_Y/PA,D_P_Passing_1st_D,D_R_Att,D_R_Yards,D_R_TD,D_R_Y/A,D_R_1st_D,D_Pe,D_Pe_Yards,D_Pe_1st_D,D_Scoring_Drives,D_TD_%,D_Expected_Points,D_x,D_y,Superbowl_x,Winner,Superbowl_y
0,1,Dallas Cowboys,16.0,479.0,6444.0,1092.0,5.9,20.0,9.0,368.0,422.0,619.0,4496.0,35.0,11.0,6.9,235.0,441.0,1948.0,13.0,4.4,102.0,122.0,1059.0,31.0,41.8,10.4,129.50,2021,7,16.0,332.0,5652.0,1012.0,5.6,33.0,8.0,305.0,344.0,578.0,3883.0,22.0,25.0,6.3,180.0,396.0,1769.0,12.0,4.5,90.0,118.0,943.0,35.0,31.6,17.1,31.06,NaN,NaN,0,NaN,NaN
1,2,Tampa Bay Buccaneers,16.0,470.0,6492.0,1079.0,6.0,19.0,7.0,383.0,463.0,692.0,4905.0,40.0,12.0,6.9,258.0,365.0,1587.0,16.0,4.3,100.0,95.0,864.0,25.0,43.4,10.4,194.61,2021,10,16.0,336.0,5318.0,1022.0,5.2,27.0,11.0,326.0,416.0,637.0,3855.0,24.0,16.0,5.7,204.0,340.0,1463.0,11.0,4.3,88.0,78.0,625.0,34.0,34.1,14.5,-25.01,NaN,NaN,0,NaN,NaN
2,3,Buffalo Bills,16.0,456.0,6069.0,1064.0,5.7,22.0,6.0,373.0,390.0,609.0,4030.0,34.0,16.0,6.3,221.0,428.0,2039.0,19.0,4.8,127.0,109.0,940.0,25.0,45.9,12.2,142.89,2021,2,16.0,279.0,4584.0,968.0,4.7,30.0,11.0,281.0,290.0,510.0,2766.0,11.0,19.0,5.1,135.0,425.0,1818.0,19.0,4.3,107.0,98.0,817.0,39.0,28.9,15.6,55.21,NaN,NaN,0,NaN,NaN
3,4,Kansas City Chiefs,16.0,452.0,6356.0,1060.0,6.0,25.0,12.0,391.0,421.0,631.0,4536.0,35.0,13.0,6.9,248.0,402.0,1820.0,16.0,4.5,113.0,106.0,880.0,30.0,48.1,14.4,183.83,2021,13,16.0,340.0,5908.0,1006.0,5.9,28.0,13.0,345.0,388.0,585.0,4100.0,27.0,15.0,6.7,200.0,391.0,1808.0,12.0,4.6,113.0,110.0,866.0,32.0,36.6,16.1,-95.51,NaN,NaN,0,NaN,NaN
4,5,Cincinnati Bengals,16.0,444.0,5963.0,995.0,6.0,21.0,7.0,326.0,369.0,526.0,4300.0,35.0,14.0,7.5,204.0,418.0,1663.0,16.0,4.0,90.0,68.0,588.0,32.0,43.6,10.5,119.10,2021,18,16.0,355.0,5588.0,1009.0,5.5,19.0,7.0,315.0,403.0,602.0,4051.0,24.0,12.0,6.3,205.0,366.0,1537.0,14.0,4.2,92.0,112.0,900.0,18.0,34.3,10.7,-27.17,NaN,NaN,0,NaN,NaN

In [35]:
test.drop(['Superbowl_x', 'Winner'], axis=1, inplace = True)

In [36]:
pd.set_option('display.max_rows', 500)
test.Superbowl_y = test.Superbowl_y.fillna(0)
test.Superbowl_y = test.Superbowl_y.astype('int')
test.rename(columns = {'Superbowl_y': 'Superbowl'}, inplace = True)

In [37]:
test.dtypes
test.Superbowl.sum()

4

## Modeling

In [38]:
import pylab as pl
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline 
import matplotlib.pyplot as plt

In [39]:
test.head()

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,O_P_Completions,O_P_Attempts,O_P_Yards,O_P_TD,O_P_Int,O_P_Y/PA,O_P_Passing_1st_D,O_R_Att,O_R_Yards,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year,D_Rank,D_Games_Played,D_Points_Allowed,D_Total_Yards,D_Plays,D_Y/Play,D_TD,D_Fumbles_Lost,D_1st_D,D_P_Completions,D_P_Attempts,D_P_Yards,D_P_TD,D_P_Int,D_P_Y/PA,D_P_Passing_1st_D,D_R_Att,D_R_Yards,D_R_TD,D_R_Y/A,D_R_1st_D,D_Pe,D_Pe_Yards,D_Pe_1st_D,D_Scoring_Drives,D_TD_%,D_Expected_Points,D_x,D_y,Superbowl
0,1,Dallas Cowboys,16.0,479.0,6444.0,1092.0,5.9,20.0,9.0,368.0,422.0,619.0,4496.0,35.0,11.0,6.9,235.0,441.0,1948.0,13.0,4.4,102.0,122.0,1059.0,31.0,41.8,10.4,129.50,2021,7,16.0,332.0,5652.0,1012.0,5.6,33.0,8.0,305.0,344.0,578.0,3883.0,22.0,25.0,6.3,180.0,396.0,1769.0,12.0,4.5,90.0,118.0,943.0,35.0,31.6,17.1,31.06,NaN,NaN,0
1,2,Tampa Bay Buccaneers,16.0,470.0,6492.0,1079.0,6.0,19.0,7.0,383.0,463.0,692.0,4905.0,40.0,12.0,6.9,258.0,365.0,1587.0,16.0,4.3,100.0,95.0,864.0,25.0,43.4,10.4,194.61,2021,10,16.0,336.0,5318.0,1022.0,5.2,27.0,11.0,326.0,416.0,637.0,3855.0,24.0,16.0,5.7,204.0,340.0,1463.0,11.0,4.3,88.0,78.0,625.0,34.0,34.1,14.5,-25.01,NaN,NaN,0
2,3,Buffalo Bills,16.0,456.0,6069.0,1064.0,5.7,22.0,6.0,373.0,390.0,609.0,4030.0,34.0,16.0,6.3,221.0,428.0,2039.0,19.0,4.8,127.0,109.0,940.0,25.0,45.9,12.2,142.89,2021,2,16.0,279.0,4584.0,968.0,4.7,30.0,11.0,281.0,290.0,510.0,2766.0,11.0,19.0,5.1,135.0,425.0,1818.0,19.0,4.3,107.0,98.0,817.0,39.0,28.9,15.6,55.21,NaN,NaN,0
3,4,Kansas City Chiefs,16.0,452.0,6356.0,1060.0,6.0,25.0,12.0,391.0,421.0,631.0,4536.0,35.0,13.0,6.9,248.0,402.0,1820.0,16.0,4.5,113.0,106.0,880.0,30.0,48.1,14.4,183.83,2021,13,16.0,340.0,5908.0,1006.0,5.9,28.0,13.0,345.0,388.0,585.0,4100.0,27.0,15.0,6.7,200.0,391.0,1808.0,12.0,4.6,113.0,110.0,866.0,32.0,36.6,16.1,-95.51,NaN,NaN,0
4,5,Cincinnati Bengals,16.0,444.0,5963.0,995.0,6.0,21.0,7.0,326.0,369.0,526.0,4300.0,35.0,14.0,7.5,204.0,418.0,1663.0,16.0,4.0,90.0,68.0,588.0,32.0,43.6,10.5,119.10,2021,18,16.0,355.0,5588.0,1009.0,5.5,19.0,7.0,315.0,403.0,602.0,4051.0,24.0,12.0,6.3,205.0,366.0,1537.0,14.0,4.2,92.0,112.0,900.0,18.0,34.3,10.7,-27.17,NaN,NaN,0

In [40]:
#split into values for test and train
test.O_Rank = test.O_Rank.astype('int')
test.D_Rank = test.D_Rank.astype('int')

train_columns = ['O_Rank', 'O_Points_For', 'O_Total_Yards',
       'O_Y/Play', 'O_TO', 'O_1st_D',
       'O_P_Completions', 'O_P_Yards', 'O_P_TD', 'O_P_Int',
       'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Yards', 'O_R_TD',
       'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards', 
       'O_Scoring_Drives', 'D_Rank',
       'D_Points_Allowed', 'D_Total_Yards', 
       'D_Y/Play', 'D_TD', 'D_Fumbles_Lost', 'D_1st_D', 'D_P_Completions',
       'D_P_Yards', 'D_P_TD', 'D_P_Int', 'D_P_Y/PA',
       'D_P_Passing_1st_D', 'D_R_Yards', 'D_R_TD', 'D_R_Y/A',
       'D_R_1st_D', 'D_Pe', 'D_Pe_Yards', 'D_Scoring_Drives']


X = np.asarray(test[train_columns])
y = np.asarray(test['Superbowl'])
print(X.shape)
print(y.shape)

(224, 39)
(224,)

In [41]:
#normalize
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)

In [42]:
teams = test.loc[ :31 , 'Team']

O_rank = test.loc[0:31, 'O_Rank']
D_rank = test.loc[0:31, 'D_Rank']

X_test = X[0:32]
X_train = X[32:]

y_test = y[0:32]
y_train = y[32:]

print(X_test.shape)
print(y_test.shape)
print(X_train.shape)
print(y_train.shape)

(32, 39)
(32,)
(192, 39)
(192,)

## Logistic Regression

In [43]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn import metrics

In [44]:
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=0.01, solver='liblinear')

In [45]:
yhat = LR.predict(X_test)
yhat

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [46]:
yhat_binary = LR.predict(X_train)
print("Accuracy:",metrics.accuracy_score(y_train, yhat_binary))

Accuracy: 0.9791666666666666

In [47]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)

np.vstack((y_train, yhat_binary)).T

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [48]:
df = pd.DataFrame({'Team':teams, 'Prediction':yhat}) 
df

                        Team  Prediction
0             Dallas Cowboys           0
1       Tampa Bay Buccaneers           0
2              Buffalo Bills           0
3         Kansas City Chiefs           0
4         Cincinnati Bengals           0
5       Los Angeles Chargers           0
6         Indianapolis Colts           0
7       New England Patriots           0
8           Los Angeles Rams           0
9          Green Bay Packers           0
10         Arizona Cardinals           0
11       Philadelphia Eagles           0
12       San Francisco 49ers           0
13         Minnesota Vikings           0
14          Tennessee Titans           0
15          Baltimore Ravens           0
16          Seattle Seahawks           0
17         Las Vegas Raiders           0
18        New Orleans Saints           0
19          Cleveland Browns           0
20       Pittsburgh Steelers           0
21  Washington Football Team           0
22            Denver Broncos           0
23            Miami Dolphins           0
24             New York Jets           0
25             Chicago Bears           0
26           Atlanta Falcons           0
27             Detroit Lions           0
28         Carolina Panthers           0
29            Houston Texans           0
30           New York Giants           0
31      Jacksonville Jaguars           0

In [49]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[0.65123219, 0.34876781],
       [0.58078029, 0.41921971],
       [0.58196648, 0.41803352],
       [0.64268847, 0.35731153],
       [0.61857986, 0.38142014],
       [0.64397447, 0.35602553],
       [0.6097771 , 0.3902229 ],
       [0.5783453 , 0.4216547 ],
       [0.57504564, 0.42495436],
       [0.57507056, 0.42492944],
       [0.61855618, 0.38144382],
       [0.5916641 , 0.4083359 ],
       [0.61796031, 0.38203969],
       [0.65291179, 0.34708821],
       [0.63759446, 0.36240554],
       [0.64788951, 0.35211049],
       [0.63959198, 0.36040802],
       [0.65217662, 0.34782338],
       [0.59933609, 0.40066391],
       [0.62890451, 0.37109549],
       [0.66683384, 0.33316616],
       [0.6445549 , 0.3554451 ],
       [0.60778713, 0.39221287],
       [0.64711224, 0.35288776],
       [0.67376012, 0.32623988],
       [0.63624389, 0.36375611],
       [0.66857647, 0.33142353],
       [0.66576433, 0.33423567],
       [0.63484868, 0.36515132],
       [0.67368544, 0.32631456],
       [0.64100973, 0.35899027],
       [0.66945193, 0.33054807]])

In [50]:
df2 = pd.DataFrame({'Team':teams, 'Prediction':yhat_prob[:,1], 'O_Rank':O_rank, 'D_rank':D_rank }) 
df2

                        Team  Prediction  O_Rank  D_rank
0             Dallas Cowboys    0.348768       1       7
1       Tampa Bay Buccaneers    0.419220       2      10
2              Buffalo Bills    0.418034       3       2
3         Kansas City Chiefs    0.357312       4      13
4         Cincinnati Bengals    0.381420       5      18
5       Los Angeles Chargers    0.356026       6      26
6         Indianapolis Colts    0.390223       7      12
7       New England Patriots    0.421655       8       1
8           Los Angeles Rams    0.424954       9      15
9          Green Bay Packers    0.424929      10       9
10         Arizona Cardinals    0.381444      11       5
11       Philadelphia Eagles    0.408336      12       8
12       San Francisco 49ers    0.382040      13      14
13         Minnesota Vikings    0.347088      14      25
14          Tennessee Titans    0.362406      15       6
15          Baltimore Ravens    0.352110      16      20
16          Seattle Seahawks    0.360408      17      11
17         Las Vegas Raiders    0.347823      18      24
18        New Orleans Saints    0.400664      19       4
19          Cleveland Browns    0.371095      20      17
20       Pittsburgh Steelers    0.333166      21      22
21  Washington Football Team    0.355445      22      28
22            Denver Broncos    0.392213      23       3
23            Miami Dolphins    0.352888      24      16
24             New York Jets    0.326240      25      32
25             Chicago Bears    0.363756      26      21
26           Atlanta Falcons    0.331424      27      29
27             Detroit Lions    0.334236      28      30
28         Carolina Panthers    0.365151      29      19
29            Houston Texans    0.326315      30      27
30           New York Giants    0.358990      31      23
31      Jacksonville Jaguars    0.330548      32      31

In [51]:
df2 = df2.sort_values(by = ['Prediction'], ascending = False)
df2['Prediction_Rank'] = df2['Prediction'].rank(ascending = False)

df2

                        Team  Prediction  O_Rank  D_rank  Prediction_Rank
8           Los Angeles Rams    0.424954       9      15              1.0
9          Green Bay Packers    0.424929      10       9              2.0
7       New England Patriots    0.421655       8       1              3.0
1       Tampa Bay Buccaneers    0.419220       2      10              4.0
2              Buffalo Bills    0.418034       3       2              5.0
11       Philadelphia Eagles    0.408336      12       8              6.0
18        New Orleans Saints    0.400664      19       4              7.0
22            Denver Broncos    0.392213      23       3              8.0
6         Indianapolis Colts    0.390223       7      12              9.0
12       San Francisco 49ers    0.382040      13      14             10.0
10         Arizona Cardinals    0.381444      11       5             11.0
4         Cincinnati Bengals    0.381420       5      18             12.0
19          Cleveland Browns    0.371095      20      17             13.0
28         Carolina Panthers    0.365151      29      19             14.0
25             Chicago Bears    0.363756      26      21             15.0
14          Tennessee Titans    0.362406      15       6             16.0
16          Seattle Seahawks    0.360408      17      11             17.0
30           New York Giants    0.358990      31      23             18.0
3         Kansas City Chiefs    0.357312       4      13             19.0
5       Los Angeles Chargers    0.356026       6      26             20.0
21  Washington Football Team    0.355445      22      28             21.0
23            Miami Dolphins    0.352888      24      16             22.0
15          Baltimore Ravens    0.352110      16      20             23.0
0             Dallas Cowboys    0.348768       1       7             24.0
17         Las Vegas Raiders    0.347823      18      24             25.0
13         Minnesota Vikings    0.347088      14      25             26.0
27             Detroit Lions    0.334236      28      30             27.0
20       Pittsburgh Steelers    0.333166      21      22             28.0
26           Atlanta Falcons    0.331424      27      29             29.0
31      Jacksonville Jaguars    0.330548      32      31             30.0
29            Houston Texans    0.326315      30      27             31.0
24             New York Jets    0.326240      25      32             32.0

## ADABOOST

In [52]:
# Load libraries
from sklearn.ensemble import AdaBoostClassifier
from sklearn import datasets
# Import train_test_split function
from sklearn.model_selection import train_test_split
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
from sklearn.ensemble import AdaBoostClassifier

# Import Support Vector Classifier
from sklearn.svm import SVC
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

In [53]:
svc=SVC(probability=True, kernel='linear')

# Create adaboost classifer object
ada =AdaBoostClassifier(n_estimators=20, base_estimator=svc,learning_rate=1)

#abc = AdaBoostClassifier(n_estimators=30, learning_rate=1)

# Train Adaboost Classifer
model = ada.fit(X_train, y_train)

In [54]:
#Predict the response for test dataset
y_pred_binary = model.predict(X_train)
y_pred = model.predict_proba(X_test)
y_pred

array([[0.9752409 , 0.0247591 ],
       [0.97447803, 0.02552197],
       [0.97489138, 0.02510862],
       [0.97589193, 0.02410807],
       [0.97659809, 0.02340191],
       [0.97784431, 0.02215569],
       [0.97557463, 0.02442537],
       [0.97483131, 0.02516869],
       [0.97610424, 0.02389576],
       [0.97554109, 0.02445891],
       [0.97553115, 0.02446885],
       [0.97662   , 0.02338   ],
       [0.97654122, 0.02345878],
       [0.97807698, 0.02192302],
       [0.97702838, 0.02297162],
       [0.97739105, 0.02260895],
       [0.97823842, 0.02176158],
       [0.97828854, 0.02171146],
       [0.97701564, 0.02298436],
       [0.97760821, 0.02239179],
       [0.97917935, 0.02082065],
       [0.97889219, 0.02110781],
       [0.9768428 , 0.0231572 ],
       [0.97807242, 0.02192758],
       [0.9806376 , 0.0193624 ],
       [0.9787984 , 0.0212016 ],
       [0.97984289, 0.02015711],
       [0.98004994, 0.01995006],
       [0.97870093, 0.02129907],
       [0.98048112, 0.01951888],
       [0.97916733, 0.02083267],
       [0.98091136, 0.01908864]])

In [55]:
df3 = pd.DataFrame({'Team':teams, 'Prediction':y_pred[:,1], 'O_Rank':O_rank, 'D_rank':D_rank }) 
df3['Prediction_Rank'] = df3['Prediction'].rank(ascending = False)
df3 = df3.sort_values(by = ['Prediction'], ascending = False)
df3

                        Team  Prediction  O_Rank  D_rank  Prediction_Rank
1       Tampa Bay Buccaneers    0.025522       2      10              1.0
7       New England Patriots    0.025169       8       1              2.0
2              Buffalo Bills    0.025109       3       2              3.0
0             Dallas Cowboys    0.024759       1       7              4.0
10         Arizona Cardinals    0.024469      11       5              5.0
9          Green Bay Packers    0.024459      10       9              6.0
6         Indianapolis Colts    0.024425       7      12              7.0
3         Kansas City Chiefs    0.024108       4      13              8.0
8           Los Angeles Rams    0.023896       9      15              9.0
12       San Francisco 49ers    0.023459      13      14             10.0
4         Cincinnati Bengals    0.023402       5      18             11.0
11       Philadelphia Eagles    0.023380      12       8             12.0
22            Denver Broncos    0.023157      23       3             13.0
18        New Orleans Saints    0.022984      19       4             14.0
14          Tennessee Titans    0.022972      15       6             15.0
15          Baltimore Ravens    0.022609      16      20             16.0
19          Cleveland Browns    0.022392      20      17             17.0
5       Los Angeles Chargers    0.022156       6      26             18.0
23            Miami Dolphins    0.021928      24      16             19.0
13         Minnesota Vikings    0.021923      14      25             20.0
16          Seattle Seahawks    0.021762      17      11             21.0
17         Las Vegas Raiders    0.021711      18      24             22.0
28         Carolina Panthers    0.021299      29      19             23.0
25             Chicago Bears    0.021202      26      21             24.0
21  Washington Football Team    0.021108      22      28             25.0
30           New York Giants    0.020833      31      23             26.0
20       Pittsburgh Steelers    0.020821      21      22             27.0
26           Atlanta Falcons    0.020157      27      29             28.0
27             Detroit Lions    0.019950      28      30             29.0
29            Houston Texans    0.019519      30      27             30.0
24             New York Jets    0.019362      25      32             31.0
31      Jacksonville Jaguars    0.019089      32      31             32.0

In [56]:
print("Accuracy:",metrics.accuracy_score(y_train, y_pred_binary))

Accuracy: 0.9791666666666666