In [1]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

import warnings
warnings.filterwarnings('ignore')

In [15]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
nfl_elo_df = pd.read_csv(Path('Resources/nfl_elo.csv'), index_col='date', parse_dates = True, infer_datetime_format=True)

# Review the DataFrame
nfl_elo_df.head()

,season,neutral,playoff,team1,team2,elo1_pre,elo2_pre,elo_prob1,elo_prob2,elo1_post,...,qb2_game_value,qb1_value_post,qb2_value_post,qbelo1_post,qbelo2_post,score1,score2,quality,importance,total_rating
date,,,,,,,,,,,,,,,,,,,,,
1920-09-26,1920,0,NaN,RII,STP,1503.947,1300.0,0.824651,0.175349,1516.108,...,NaN,NaN,NaN,NaN,NaN,48.0,0.0,NaN,NaN,NaN
1920-10-03,1920,0,NaN,RCH,ABU,1503.420,1300.0,0.824212,0.175788,1510.934,...,NaN,NaN,NaN,NaN,NaN,10.0,0.0,NaN,NaN,NaN
1920-10-03,1920,0,NaN,AKR,WHE,1503.420,1300.0,0.824212,0.175788,1515.278,...,NaN,NaN,NaN,NaN,NaN,43.0,0.0,NaN,NaN,NaN
1920-10-03,1920,0,NaN,CBD,PTQ,1504.688,1300.0,0.825267,0.174733,1516.803,...,NaN,NaN,NaN,NaN,NaN,48.0,0.0,NaN,NaN,NaN
1920-10-03,1920,0,NaN,CHI,MUT,1368.333,1300.0,0.682986,0.317014,1386.533,...,NaN,NaN,NaN,NaN,NaN,20.0,0.0,NaN,NaN,NaN

In [24]:
# Selection of just certain features to try and test a potential model

nfl_2016_2021_df = nfl_elo_df.loc['2016-09-08':'2021-02-07'][['team1', 'team2', 'elo1_pre', 'elo2_pre', 'elo_prob1', 'elo_prob2', 'score1', 'score2']]

In [25]:
nfl_2016_2021_df.head()

,team1,team2,elo1_pre,elo2_pre,elo_prob1,elo_prob2,score1,score2
date,,,,,,,,
2016-09-08,DEN,CAR,1637.113158,1633.579265,0.597369,0.402631,21.0,20.0
2016-09-11,NYJ,CIN,1522.163909,1578.458118,0.512526,0.487474,22.0,23.0
2016-09-11,PHI,CLE,1487.849378,1394.516013,0.713295,0.286705,29.0,10.0
2016-09-11,TEN,MIN,1349.452615,1567.160011,0.293374,0.706626,16.0,25.0
2016-09-11,BAL,BUF,1475.498332,1518.808090,0.531174,0.468826,13.0,7.0

In [28]:
# Create an ouptut variable: FavoredWin
# This variable will be a 1 if the favored team wins and a 0 if the favored team loses
# The favored team is that which has the higher Elo score pre-game

favored_win = []

for i in range(len(nfl_2016_2021_df)):
    if (nfl_2016_2021_df.loc[i, 'elo1_pre'] > nfl_2016_2021_df.loc[i, 'elo2_pre']) and (nfl_2016_2021_df.loc[i, 'score1'] > nfl_2016_2021_df.loc[i, 'score2']):
        favored_win.append('1')
    elif (nfl_2016_2021_df.loc[i, 'elo2_pre'] > nfl_2016_2021_df.loc[i, 'elo1_pre']) and (nfl_2016_2021_df.loc[i, 'score2'] > nfl_2016_2021_df.loc[i, 'score1']):
        favored_win.append('1')
    else:
        favored_win.append('0')

KeyError: 0